:ersion: '3'

services:
  varnish_nginx:
    image: "nginx:alpine"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.varnish.nginx.conf:/etc/nginx/nginx.conf"
      - "./tls/:/etc/eisenhardt/tls"
    depends_on:
      - "varnish"

  nginx:
    image: "nginx:alpine"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.nginx.conf:/etc/nginx/nginx.conf"
      - "../pub:/mnt/magento/pub"
    depends_on:
      - "appserver"

  appserver:
    image: "maxbucknell/php:{{version}}"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.php.ini:/usr/local/etc/php/php.ini"
      - "./servers/eisenhardt.php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "..:/mnt/magento"
    depends_on:
      - "database"
      - "cache"
      - "session"
      - "rabbitmq"

  database:
    image: percona:5.6
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.my.cnf:/etc/mysql/my.cnf"
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  cache_redis:
    image: "redis:alpine"
    networks:
      - "magento"

  session_redis:
    image: "redis:alpine"
    networks:
      - "magento"

  varnish:
    image: "maxbucknell/varnish:latest"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.varnish.vcl:/etc/varnish/default.vcl"
    depends_on:
      - "nginx"

  rabbitmq:
    image: "rabbitmq:management-alpine"
    hostname: "rabbitmq"
    networks:
      - "magento"

  elasticsearch:
    image: "elasticsearch:5"
    networks:
    - "magento"

  kibana:
    image: "kibana:5"
    networks:
    - "magento"

networks:
  magento:
    driver: bridge
