version: '2'

services:
  varnish_webserver:
    image: "nginx:alpine"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.varnish.nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - "magento_pagecache"

  magento_webserver:
    image: "nginx:alpine"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - "magento_appserver"

  magento_appserver:
    image: "maxbucknell/php:{{version}}"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.php.ini:/usr/local/etc/php/php.ini"
      - "./servers/eisenhardt.php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf"
    depends_on:
      - "magento_database"
      - "magento_cache"
      - "magento_session"
      - "magento_messagequeue"

  magento_database:
    image: percona:5.6
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.my.cnf:/etc/mysql/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  magento_cache:
    image: "redis:alpine"
    networks:
      - "magento"
  magento_session:
    image: "redis:alpine"
    networks:
      - "magento"

  magento_pagecache:
    image: "maxbucknell/varnish:latest"
    networks:
      - "magento"
    volumes:
      - "./servers/eisenhardt.varnish.vcl:/etc/varnish/default.vcl"
    depends_on:
      - "magento_webserver"

  magento_messagequeue:
    image: "rabbitmq:management-alpine"
    networks:
      - "magento"

networks:
  magento:
    driver: bridge
