version: '2'

services:
  magento_webserver:
    image: "nginx:alpine"
    networks:
      - "magento"
    volumes:
      - "./servers/rd.nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - "magento_appserver"

  magento_appserver:
    image: "maxbucknell/php:7.0"
    networks:
      - "magento"
    volumes:
      - "./servers/rd.php.ini:/usr/local/etc/php/php.ini"
      - "./servers/rd.php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf"
    depends_on:
      - "magento_database"
      - "magento_cache"
      - "magento_fpc"
      - "magento_session"
      - "magento_messagequeue"

  magento_database:
    image: percona:5.6
    networks:
      - "magento"
    volumes:
      - "./servers/rd.my.cnf:/etc/mysql/my.cnf"
    environment:
      MYSQL_ROOT_PASSWORD: "root"

  magento_cache:
    image: "redis:alpine"
    networks:
      - "magento"
  magento_fpc:
    image: "redis:alpine"
    networks:
      - "magento"
  magento_session:
    image: "redis:alpine"
    networks:
      - "magento"

  magento_messagequeue:
    image: "rabbitmq:management-alpine"
    networks:
      - "magento"

networks:
  magento:
    driver: bridge
