version: '2'

services:
  magento_webserver:
    depends_on:
      - "magento_appserver_debug"

  magento_appserver:
    volumes:
      - "./servers/mailhog.rd.php.ini:/usr/local/etc/php/conf.d/mailhog.rd.php.ini"
    depends_on:
      - "magento_mail"

  magento_appserver_debug:
    image: "redboxdigital/php:7.0-xdebug"
    networks:
      - "magento"
    volumes_from:
      - "magento_appserver"
    depends_on:
      - "magento_appserver"

  magento_mail:
    image: "mailhog/mailhog"
    user: "root"
    expose:
      - "25"
      - "80"
    environment:
      MH_SMTP_BIND_ADDR: "0.0.0.0:25"
      MH_UI_BIND_ADDR: "0.0.0.0:80"
      MH_API_BIND_ADDR: "0.0.0.0:80"
      MH_HOSTNAME: "magento_mail"
      MH_MAILDIR_PATH: "/mnt/mail"
      MH_STORAGE: "maildir"
    volumes:
      - "./mail:/mnt/mail"
    networks:
      - "magento"

  magento_appserver:
    depends_on:
      - "magento_mail"
